-- Seed demo profile and Circles for Circle Match

insert into public.profiles (id, display_name, email, preferences)
values (
  '11111111-1111-1111-1111-111111111111',
  'Amina Okonkwo',
  'amina.demo@leanin.connect',
  null
)
on conflict (id) do update
set display_name = excluded.display_name,
    email = excluded.email;

insert into public.circles (
  id, slug, name, category, description, who_its_for, topics, support_types,
  career_stages, format, frequency, location, schedule, member_count, image_tone,
  leader, members
) values
(
  '22222222-2222-2222-2222-222222222201',
  'tech-leadership-collective',
  'Tech Leadership Collective',
  'Technology & Leadership',
  'A Circle for women growing into technical leadership—engineering managers, staff+ ICs, and rising product technologists who want candid peer coaching.',
  'Mid-career and senior women in technology who want to lead with clarity, advocate for themselves, and build durable influence.',
  array['growing-in-technology', 'growing-as-a-leader', 'building-confidence'],
  array['peer-support', 'leadership-growth', 'skill-building'],
  array['mid-career', 'senior-leader'],
  'virtual',
  'biweekly',
  'Virtual · Global',
  'Every other Tuesday · 12:00–1:00 PM PT',
  9,
  'burgundy',
  '{"name":"Priya Nandakumar","title":"Director of Engineering","bio":"Priya has led distributed engineering teams for a decade and facilitates with warmth and precision.","initials":"PN"}'::jsonb,
  '[{"name":"Jordan Lee","role":"Staff Engineer","initials":"JL"},{"name":"Samira Haddad","role":"EM","initials":"SH"},{"name":"Nora Chen","role":"Product Lead","initials":"NC"}]'::jsonb
),
(
  '22222222-2222-2222-2222-222222222202',
  'returning-with-confidence',
  'Returning with Confidence',
  'Career Returners',
  'Rebuild momentum after a career pause. This Circle blends practical re-entry planning with encouragement from women who have been there.',
  'Women returning to work after caregiving, relocation, or a deliberate career break.',
  array['returning-to-work', 'building-confidence', 'finding-mentorship'],
  array['peer-support', 'accountability', 'networking'],
  array['returning-to-work', 'career-transition', 'mid-career'],
  'hybrid',
  'biweekly',
  'San Francisco, CA',
  '1st & 3rd Thursday · 6:00–7:15 PM PT',
  8,
  'blush',
  '{"name":"Elena Vasquez","title":"People Ops Leader","bio":"Elena returned to work after five years and now coaches others through the same transition.","initials":"EV"}'::jsonb,
  '[{"name":"Maya Brooks","role":"Marketing","initials":"MB"},{"name":"Hana Kim","role":"Analyst","initials":"HK"},{"name":"Ruth Adeyemi","role":"PM","initials":"RA"}]'::jsonb
),
(
  '22222222-2222-2222-2222-222222222203',
  'founders-first-circle',
  'Founders First Circle',
  'Entrepreneurship',
  'For women building companies—pre-seed to Series A—who want honest conversation about fundraising, hiring, and sustainable ambition.',
  'Founders and aspiring entrepreneurs seeking peer accountability and practical founder wisdom.',
  array['entrepreneurship', 'growing-as-a-leader', 'work-life-integration'],
  array['accountability', 'networking', 'leadership-growth'],
  array['founder', 'mid-career', 'senior-leader'],
  'virtual',
  'monthly',
  'Virtual · Americas',
  'First Wednesday · 5:00–6:30 PM ET',
  11,
  'sand',
  '{"name":"Imani Cole","title":"Founder & CEO","bio":"Imani has raised two rounds and believes Circles should feel like a trusted board of peers.","initials":"IC"}'::jsonb,
  '[{"name":"Leah Ortiz","role":"Founder","initials":"LO"},{"name":"Quinn Patel","role":"Co-founder","initials":"QP"},{"name":"Aisha Rahman","role":"Solo founder","initials":"AR"}]'::jsonb
),
(
  '22222222-2222-2222-2222-222222222204',
  'midcareer-momentum',
  'Mid-Career Momentum',
  'Career Growth',
  'Navigate the messy middle: scope expansion, sponsorship, and deciding what leadership looks like for you next.',
  'Women 7–15 years into their careers who want thoughtful peers—not just another networking mixer.',
  array['growing-as-a-leader', 'finding-mentorship', 'navigating-career-transition', 'building-confidence'],
  array['peer-support', 'leadership-growth', 'skill-building'],
  array['mid-career', 'career-transition'],
  'in-person',
  'monthly',
  'New York, NY',
  'Second Monday · 6:30–8:00 PM ET',
  10,
  'rose',
  '{"name":"Danielle Wright","title":"VP, Strategy","bio":"Danielle facilitates with editorial clarity and a bias toward actionable takeaways.","initials":"DW"}'::jsonb,
  '[{"name":"Sofia Alvarez","role":"Director","initials":"SA"},{"name":"Grace Park","role":"Counsel","initials":"GP"},{"name":"Talia Green","role":"Design Lead","initials":"TG"}]'::jsonb
),
(
  '22222222-2222-2222-2222-222222222205',
  'work-life-integration-lab',
  'Work-Life Integration Lab',
  'Wellbeing & Boundaries',
  'Experiment with boundaries, energy management, and values-aligned ambition in a judgment-free Circle.',
  'Women who want sustainable success—especially caregivers, dual-career partners, and high performers resetting their pace.',
  array['work-life-integration', 'building-confidence', 'returning-to-work'],
  array['peer-support', 'accountability'],
  array['mid-career', 'returning-to-work', 'senior-leader'],
  'virtual',
  'weekly',
  'Virtual · Global',
  'Wednesdays · 8:00–8:45 AM PT',
  7,
  'sage',
  '{"name":"Camille Dubois","title":"Executive Coach","bio":"Camille helps members design experiments they can actually keep.","initials":"CD"}'::jsonb,
  '[{"name":"Bee Tanaka","role":"Manager","initials":"BT"},{"name":"Olivia Grant","role":"Consultant","initials":"OG"},{"name":"Nadia Farouk","role":"Physician","initials":"NF"}]'::jsonb
),
(
  '22222222-2222-2222-2222-222222222206',
  'career-transition-circle-chicago',
  'Career Transition Circle · Chicago',
  'Career Transitions',
  'A grounded, in-person Circle for women changing industries, functions, or levels—with space to process uncertainty and plan next moves.',
  'Women actively navigating a career transition who want local community and practical peer feedback.',
  array['navigating-career-transition', 'finding-mentorship', 'building-confidence'],
  array['peer-support', 'networking', 'skill-building'],
  array['career-transition', 'early-career', 'mid-career'],
  'in-person',
  'biweekly',
  'Chicago, IL',
  'Alternating Saturdays · 10:00–11:30 AM CT',
  12,
  'slate',
  '{"name":"Keisha Morgan","title":"Career Strategist","bio":"Keisha has guided hundreds of transitions and keeps meetings focused and kind.","initials":"KM"}'::jsonb,
  '[{"name":"Anna Petrov","role":"UX","initials":"AP"},{"name":"Michelle Torres","role":"Sales","initials":"MT"},{"name":"Fatima Diallo","role":"Ops","initials":"FD"}]'::jsonb
),
(
  '22222222-2222-2222-2222-222222222207',
  'early-career-amplify',
  'Early Career Amplify',
  'Early Career',
  'Build confidence, communication skills, and a professional network in your first chapters of work.',
  'Women in the first 1–5 years of their careers who want mentorship energy and peer community.',
  array['building-confidence', 'finding-mentorship', 'growing-as-a-leader'],
  array['skill-building', 'networking', 'peer-support'],
  array['early-career'],
  'hybrid',
  'monthly',
  'Austin, TX',
  'Last Tuesday · 6:00–7:30 PM CT',
  14,
  'blush',
  '{"name":"Jasmine Brooks","title":"Program Manager","bio":"Jasmine creates a welcoming space for questions you might not ask at work.","initials":"JB"}'::jsonb,
  '[{"name":"Zoe Nguyen","role":"Associate","initials":"ZN"},{"name":"Carla Mendes","role":"Coordinator","initials":"CM"},{"name":"Priya Shah","role":"Analyst","initials":"PS"}]'::jsonb
),
(
  '22222222-2222-2222-2222-222222222208',
  'women-in-product-tech',
  'Women in Product & Tech',
  'Technology',
  'Cross-functional Circle for PMs, designers, and engineers who want to grow influence and craft in tech.',
  'Women in product and technology roles seeking peer learning and sponsorship conversations.',
  array['growing-in-technology', 'finding-mentorship', 'growing-as-a-leader'],
  array['skill-building', 'networking', 'peer-support'],
  array['early-career', 'mid-career'],
  'virtual',
  'biweekly',
  'Virtual · Global',
  'Thursdays · 11:00 AM–12:00 PM ET (biweekly)',
  13,
  'burgundy',
  '{"name":"Rebecca Cho","title":"Senior PM","bio":"Rebecca balances craft deep-dives with honest career conversation.","initials":"RC"}'::jsonb,
  '[{"name":"Ines Moreau","role":"Designer","initials":"IM"},{"name":"Kayla Johnson","role":"Engineer","initials":"KJ"},{"name":"Mei Lin","role":"PM","initials":"ML"}]'::jsonb
)
on conflict (id) do update
set
  slug = excluded.slug,
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  who_its_for = excluded.who_its_for,
  topics = excluded.topics,
  support_types = excluded.support_types,
  career_stages = excluded.career_stages,
  format = excluded.format,
  frequency = excluded.frequency,
  location = excluded.location,
  schedule = excluded.schedule,
  member_count = excluded.member_count,
  image_tone = excluded.image_tone,
  leader = excluded.leader,
  members = excluded.members;
